### ISSUE TITLE
Manipulating malformed NSEC3 RRs causes Perl to crash

### ISSUE THREAD

**Issue by marc-vanderwal** [zonemaster/zonemaster-ldns#174]
Calling the `Zonemaster::LDNS::RR::NSEC3::covers` method on `Zonemaster::LDNS::RR::NSEC3` objects instantiated from NSEC3 resource records whose “next hashed owner name” RDATA field is empty causes Perl to crash with the following output:

```
perl: ./rdata.c:33: ldns_rdf_get_type: Assertion `rd != NULL' failed.
Aborted
```

## Example

The following examples use a version of `Zonemaster::LDNS` linked against an external custom build of `ldns`, version 1.8.3, compiled with debugging symbols.

Script:
```perl
#!/usr/bin/env perl

use strict;
use v5.10;

use Zonemaster::LDNS;

# This will crash
say Zonemaster::LDNS::RR->new(
    q{one.example. 0 IN NSEC3 \# 15 01 00 0001 01 AB 00 0006 400000000002}
)->covers("example");
```

Backtrace:
```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c6c859 in __GI_abort () at abort.c:79
#2  0x00007ffff7c6c729 in __assert_fail_base (fmt=0x7ffff7e02588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x7ffff769e27a "rd != NULL", file=0x7ffff769e270 "./rdata.c", line=33, function=<optimized out>)
    at assert.c:92
#3  0x00007ffff7c7dfd6 in __GI___assert_fail (assertion=0x7ffff769e27a "rd != NULL", file=0x7ffff769e270 "./rdata.c",
    line=33, function=0x7ffff769e520 <__PRETTY_FUNCTION__.24937> "ldns_rdf_get_type") at assert.c:101
#4  0x00007ffff767edc5 in ldns_rdf_get_type (rd=0x0) at ./rdata.c:33
#5  0x00007ffff765409a in ldns_dname_cat (rd1=0x0, rd2=0x555555a849d0) at ./dname.c:96
#6  0x00007ffff76585e0 in ldns_nsec_covers_name (nsec=0x555555a84990, name=0x5555558d5ec0) at ./dnssec.c:1530
#7  0x00007ffff76c2b80 in XS_Zonemaster__LDNS__RR__NSEC3_covers (my_perl=<optimized out>, cv=<optimized out>)
    at src/LDNS.xs:2355
#8  0x000055555565da10 in Perl_pp_entersub ()
#9  0x0000555555654166 in Perl_runops_standard ()
#10 0x00005555555c791c in perl_run ()
#11 0x000055555559d432 in main ()
```

**Comment by marc-vanderwal** [comment]
These are actually two related sub-issues. I have updated the description with more information.

**Comment by marc-vanderwal** [comment]
The second example seems to be an unrelated issue, actually. Here it’s looking like the culprit is LDNS, but in #175 it’s our XS code that is at fault.

**Comment by marc-vanderwal** [comment]
A PR addressing this issue was merged. Let’s close this.
