### ISSUE TITLE
Calling Zonemaster::LDNS::RR::covers() with root domain causes Perl to crash

### ISSUE THREAD

**Issue by marc-vanderwal** [zonemaster/zonemaster-ldns#175]
Given a `Zonemaster::LDNS::RR::NSEC3` object constructed from well-formed data, a call to the `covers` method, suppyling `"."` as argument, causes an assertion failure:

```
perl: ./rdata.c:33: ldns_rdf_get_type: Assertion `rd != NULL' failed.
Aborted
```

This bug is similar to #174, but the cause is unrelated.

## Example

When running the following script, Perl crashes:

```perl
#!/usr/bin/env perl

use Zonemaster::LDNS;

say Zonemaster::LDNS::RR->new(
    q{RUU6LA0MNBUDDQRRH3PE2ENBLB9G5LME.van-der-wal.fr. 60 IN NSEC3 (
        1 0 8 A46C64ADD6FD2A4D S1OP0M2467BA1BFHAQQKLV3FA3NU5QNV
        NS SOA MX TXT RRSIG DNSKEY NSEC3PARAM )}
)->covers(".");
```

Using a version of `Zonemaster::LDNS` linked against an external custom build of LDNS, version 1.8.3, with debugging symbols, the backtrace is as follows:

```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c6c859 in __GI_abort () at abort.c:79
#2  0x00007ffff7c6c729 in __assert_fail_base (fmt=0x7ffff7e02588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x7ffff769e27a "rd != NULL", file=0x7ffff769e270 "./rdata.c", line=33, function=<optimized out>)
    at assert.c:92
#3  0x00007ffff7c7dfd6 in __GI___assert_fail (assertion=0x7ffff769e27a "rd != NULL", file=0x7ffff769e270 "./rdata.c",
    line=33, function=0x7ffff769e520 <__PRETTY_FUNCTION__.24937> "ldns_rdf_get_type") at assert.c:101
#4  0x00007ffff767edc5 in ldns_rdf_get_type (rd=0x0) at ./rdata.c:33
#5  0x00007ffff76540ab in ldns_dname_cat (rd1=0x5555558facc0, rd2=0x0) at ./dname.c:97
#6  0x00007ffff76c2b75 in XS_Zonemaster__LDNS__RR__NSEC3_covers (my_perl=<optimized out>, cv=<optimized out>)
    at src/LDNS.xs:2354
#7  0x000055555565da10 in Perl_pp_entersub ()
#8  0x0000555555654166 in Perl_runops_standard ()
#9  0x00005555555c791c in perl_run ()
#10 0x000055555559d432 in main ()
```

**Comment by marc-vanderwal** [comment]
A PR fixing this specific issue has been merged. Let’s close this issue.
